GRANT SELECT ON  VW_NFSE_DUPGESTONLINE_SOLUTI TO GATEWAY;
GRANT EXECUTE ON  VW_NFSE_DUPGESTONLINE_SOLUTI TO GATEWAY;
GRANT UPDATE ON  VW_NFSE_DUPGESTONLINE_SOLUTI TO GATEWAY;
GRANT INSERT ON  VW_NFSE_DUPGESTONLINE_SOLUTI TO GATEWAY;
GRANT DELETE ON  VW_NFSE_DUPGESTONLINE_SOLUTI TO GATEWAY;