create or replace PROCEDURE STP_SNK_DELPEDPEND_SOLUTI
 AS
BEGIN
 DECLARE
   P_NUNOTA    INT;

   CURSOR PENDENTES  IS
      SELECT CAB.NUNOTA
        FROM TGFCAB CAB, TGFFIN FIN
        WHERE CAB.NUNOTA = FIN.NUNOTA(+)
          AND CAB.DTNEG >= '01-01-2021'
          AND CAB.TIPMOV = 'P'
          AND CAB.PENDENTE = 'S'
          AND SYSDATE > (FIN.DTVENC + 10)
          AND CAB.VLRDESCTOTITEM < (SELECT SUM(TGFITE.VLRTOT) FROM TGFITE WHERE TGFITE.NUNOTA = CAB.NUNOTA)
          AND NOT EXISTS (SELECT 1 
                             FROM TGFITE ITE 
                            WHERE ITE.NUNOTA = CAB.NUNOTA 
                              AND AD_QTDENTREGUECERTIF IS NOT NULL)
          AND  NOT EXISTS (SELECT 1 
                             FROM TGFVAR VAR
                            WHERE VAR.NUNOTAORIG = CAB.NUNOTA)
          AND  NOT EXISTS (SELECT 1 
                             FROM TGFFIN FIN
                            WHERE FIN.NUNOTA = CAB.NUNOTA 
                              AND FIN.DHBAIXA IS NOT NULL
                              AND FIN.VLRBAIXA > 0)
          AND      EXISTS (SELECT 1
                             FROM AD_PARAMETROPRJ PRJ
                            WHERE CODPROJ = CAB.CODPROJ 
                              AND PRJ.NUPARAMETRO = 152); 

 BEGIN

   OPEN PENDENTES;
   LOOP
     FETCH PENDENTES INTO P_NUNOTA;

    IF STP_GET_ATUALIZANDO THEN
        RETURN;
    END IF;

    /*GRAVANDO O LOG DOS PEDIDOS DELETADOS*/
    INSERT INTO AD_LOGPEDDEL (NUNOTA, VLRNOTA, DTNEG, CODVEND, CODTIPOPER, CODPARC, CODPROJ, DTDEL)
    SELECT NUNOTA, VLRNOTA, DTNEG, CODVEND, CODTIPOPER, CODPARC, CODPROJ, SYSDATE
    FROM   TGFCAB 
    WHERE  NUNOTA = P_NUNOTA;

     /*Deletando os registros */
     DELETE
     FROM TGFREN
     WHERE NUFIN IN (SELECT NUFIN FROM TGFFIN WHERE NUNOTA = P_NUNOTA);
     DELETE FROM TGFFIN WHERE NUNOTA = P_NUNOTA;
     DELETE FROM TGFCAB WHERE NUNOTA = P_NUNOTA;

   EXIT WHEN PENDENTES%NOTFOUND;
   END LOOP;
   CLOSE PENDENTES;
 END;
END;