SELECT CODPROD, 
       DESCRPROD, 
       (SELECT DESCRGRUPOPROD 
          FROM TGFGRU 
         WHERE TGFGRU.CODGRUPOPROD = TGFPRO.codgrupoprod) AS GRUPO,
       CASE USOPROD WHEN 'S' THEN 'SERVICO'
                    WHEN 'R' THEN 'REVENDA'
                    WHEN 'V' THEN 'VENDA' END AS TIPO_PRODUTO
FROM  TGFPRO 
WHERE USOPROD IN ('V', 'S', 'R')
  AND CODGRUPOPROD IN (100101, 200101, 200102, 200103, 200104, 200105)
ORDER BY CODPROD ASC