SELECT  SUM(VALOR - REC)  AS VALOR,
        SUM(REC) AS REC, 
        PER, 
        ORDEM, 
        SUM(TOT) AS TOT,
        AGRUP,
        CODPROJ,
        IDENTIFICACAO,
        NOMEPARC,
        APELIDO,
        NOMECID,
        UF,
        CODPARC,
        NUNOTA AS NUNOTA, 
        CODTIPOPER as TOP  
FROM (
SELECT VW.VALOR, 
       VW.REC,
       VW.PER, 
       VW.ORDEM, 
       VW.NOMEPARC, 
       VW.TOT, 
       VW.AGRUP,
       VW.CODPROJ, 
       VW.IDENTIFICACAO,
       (SELECT APELIDO FROM TGFVEN WHERE CODVEND = VW.CODVENDRESP) AS APELIDO,
       VW.NOMECID,
       VW.UF,
       VW.CODPARC,
       VW.NUNOTA,
       VW.CODTIPOPER
FROM VW_EVOLUCAO_VENDAS_SOLUTI VW
WHERE TRUNC(VW.DTFATUR) >=  :PERIODO.INI   
AND   TRUNC(VW.DTFATUR) <=  :PERIODO.FIN
AND   VW.CODEMP IN :EMPRESA
AND   VW.CODPROD IN :PRODUTO 
AND   ((VW.CODVENDRESP = :AGR) OR (:AGR IS NULL))
AND   ((VW.CODPARC= :PARCEIRO) OR (:PARCEIRO IS NULL))
AND   ((VW.CODTIPPARC= :PERFIL) OR (:PERFIL IS NULL))
AND   VW.PER = :PER 
AND   VW.AGRUP = :AGRUP
GROUP BY VW.PER, VW.ORDEM, VW.NOMEPARC, VW.VALOR, VW.REC, VW.TOT, 
         VW.AGRUP, VW.CODVENDRESP, VW.CODPROJ, VW.IDENTIFICACAO, VW.NOMECID, VW.UF, 
         VW.CODPARC, VW.NUNOTA, VW.CODTIPOPER

UNION ALL

SELECT  FIN.VLRDESDOB AS VALOR,
        FIN.VLRBAIXA AS REC, 
        (TO_CHAR(TRUNC(FIN.DTNEG,'DD'),'Mon/YYYY')) AS PER,
        (TO_CHAR(TRUNC(FIN.DTNEG,'DD'),'YYYYMM')) AS ORDEM,
        (SELECT NOMEPARC FROM TGFPAR WHERE CODPARC = FIN.CODPARC) AS NOMEPARC,  
        FIN.VLRDESDOB AS TOT,
        'AR POS PAGO' AS AGRUP,
        FIN.CODPROJ,
        (SELECT DISTINCT(PRJ.IDENTIFICACAO) FROM TCSPRJ PRJ WHERE PRJ.CODPROJ = FIN.CODPROJ) AS IDENTIFICACAO,
        (SELECT APELIDO FROM TGFVEN WHERE CODVEND = FIN.CODVEND) AS APELIDO,
        (SELECT NOMECID FROM TSICID WHERE CODCID =(SELECT TGFPAR.CODCID FROM TGFPAR WHERE CODPARC = FIN.CODPARC)) AS NOMECID,
        (SELECT TSIUFS.UF FROM TSIUFS WHERE TSIUFS.CODUF =
        (SELECT TSICID.UF FROM TSICID WHERE  TSICID.CODCID = (SELECT TGFPAR.CODCID FROM TGFPAR WHERE CODPARC = FIN.CODPARC))) AS UF,
         FIN.CODPARC,
         FIN.NUFIN AS NUNOTA,
         FIN.CODTIPOPER       
FROM TGFFIN FIN 
WHERE FIN.CODTIPOPER = '4016'
AND   FIN.PROVISAO = 'N'
AND   FIN.RECDESP <> 0
AND   TRUNC(FIN.DTNEG,'DD') >= :PERIODO.INI 
AND   TRUNC(FIN.DTNEG,'DD') <= :PERIODO.FIN
AND   FIN.CODEMP IN :EMPRESA
AND   ((FIN.CODVEND = :AGR) OR (:AGR IS NULL))
AND   TO_CHAR(TRUNC(FIN.DTNEG,'DD'),'Mon/YYYY') = :PER
AND   FC_DASH_AGRUP_SOL(FIN.CODPROJ, FIN.CODTIPOPER, FIN.CODCENCUS, 
      (SELECT AD_PERFIL FROM TCSPRJ WHERE CODPROJ = FIN.CODPROJ )) = :AGRUP
GROUP BY FIN.DTNEG, FIN.CODPARC,  FIN.VLRDESDOB, FIN.VLRBAIXA, FIN.CODVEND, FIN.CODPROJ, FIN.CODPARC, FIN.NUNOTA, FIN.CODTIPOPER, FIN.NUFIN    ) EVOVEND
GROUP BY PER, 
         ORDEM,
         AGRUP,
         CODPROJ,
         IDENTIFICACAO,
         NOMEPARC,
         APELIDO,
         NOMECID,
         UF,
         CODPARC,
         NUNOTA,
         CODTIPOPER  
ORDER BY 5 DESC