SELECT CAB.CODEMP,
       FIN.NUFIN,
       CAB.NUNOTA,
       CAB.CODPROJ,
       PAR.CGC_CPF,
       PAR.NOMEPARC,
       PAR.TELEFONE,
       NVL(PAR.EMAIL, PAR.EMAILNFSE) AS EMAIL,
       (SELECT TSIEND.NOMEEND FROM TSIEND WHERE CODEND = PAR.CODEND) AS ENDERECO,
       (SELECT TSIBAI.NOMEBAI FROM TSIBAI WHERE CODBAI = PAR.CODBAI) AS BAIRRO,
       (SELECT TSICID.NOMECID||' - '||
              (SELECT TSIUFS.UF FROM TSIUFS WHERE CODUF = TSICID.UF)
        FROM TSICID WHERE CODCID = PAR.CODCID ) AS CIDADE_UF,
       PAR.CEP AS CEP,
       CAB.VLRNOTA,
       CAB.DTNEG,
       CAB.DTFATUR,
       FC_LISTAPRODCONS (CAB.NUNOTA) AS LIST_COD_PRODUTOS,
       FC_LISTA_NOMEPROD_PORNOTA(CAB.NUNOTA) AS LIST_NOME_PRODUTOS,
       FIN.VLRBAIXA,
       FIN.CODTIPTIT,
       FIN.DESDOBRAMENTO,
       NVL((SELECT CGC_CPF FROM TGFPAR WHERE CODPARC = PAR.AD_CODPARC),'NÃO TEM IND') AS INDICADOR,
       FIN.DHBAIXA
FROM TGFCAB CAB, TGFPAR PAR, TGFITE ITE, TGFFIN FIN
WHERE CAB.NUNOTA = FIN.NUNOTA  
  AND CAB.NUNOTA = ITE.NUNOTA
  AND CAB.CODPARC = PAR.CODPARC
  AND CAB.CODTIPOPER = 1900
  AND CAB.DTFATUR BETWEEN :DTINI AND :DTFIN
  AND FIN.VLRBAIXA > 0
  AND FIN.DHBAIXA IS NOT NULL
  AND CAB.CODPROJ IN (SELECT CODPROJ FROM AD_PARAMETROPRJ WHERE NUPARAMETRO = 174 GROUP BY CODPROJ)
GROUP BY 
       CAB.CODEMP,
       FIN.NUFIN,
       CAB.NUNOTA,
       CAB.CODPROJ,
       PAR.CGC_CPF,
       PAR.NOMEPARC,
       CAB.VLRNOTA,
       CAB.DTNEG,
       CAB.DTFATUR,
       FIN.VLRBAIXA,
       FIN.CODTIPTIT,
       FIN.DESDOBRAMENTO,
       PAR.AD_CODPARC,
       PAR.TELEFONE,
       PAR.EMAIL, 
       PAR.EMAILNFSE,
       PAR.CODEND,
       PAR.CODBAI,
       PAR.CODCID,
       PAR.CEP,
       FIN.DHBAIXA
ORDER BY CAB.NUNOTA



