
SELECT TOT.NUBCO, TOT.HISTORICO, TOT.CODCTABCOINT, TOT.VLRLANC, TOT.DTLANC, TOT.CODTIPOPER 
FROM
(SELECT  NUBCO, HISTORICO, CODCTABCOINT, VLRLANC, DTLANC, CODTIPOPER
FROM TGFMBC
WHERE  DTALTER > '01/10/21'
  AND CODTIPOPER = 4401
  AND CONCILIADO = 'N') TOT,

(SELECT HISTORICO, CODCTABCOINT, VLRLANC, DTLANC, CODTIPOPER, COUNT(*) AS QTD
FROM TGFMBC
WHERE /*CODCTABCOINT IN (18, 561)
  AND*/ CODUSU IN (0, 2511)
  AND DTALTER > '01/10/21'
  AND CODTIPOPER = 4401
  AND CONCILIADO = 'N'
GROUP BY HISTORICO, CODCTABCOINT, VLRLANC, DTLANC, CODTIPOPER
HAVING  COUNT(*) > 1 ) CONT

WHERE TOT.HISTORICO = CONT.HISTORICO
  AND TOT.CODCTABCOINT = CONT.CODCTABCOINT
  AND TOT.VLRLANC = CONT.VLRLANC
  AND TOT.DTLANC = CONT.DTLANC
  AND TOT.CODTIPOPER = CONT.CODTIPOPER