CREATE OR REPLACE VIEW VW_EVOLUCAO_VENDAS_SOLUTI AS
SELECT 
      SUM(CAB.VLRNOTA - CAB.VLRDESCTOTITEM) AS VALOR
    , SUM((SELECT NVL(SUM(FIN.VLRBAIXA),0) 
             FROM TGFFIN FIN 
            WHERE FIN.NUNOTA = CAB.NUNOTA 
              AND FIN.RECDESP = 1 
              AND FIN.PROVISAO = 'N'  
              AND FIN.VLRBAIXA > 0)) AS REC 
    , SUM(CAB.VLRNOTA) AS TOT
    , TO_CHAR(TRUNC(CAB.DTNEG,'DD'),'Mon/YYYY') AS PER
    , TO_CHAR(TRUNC(CAB.DTNEG,'DD'),'YYYYMM') AS ORDEM
    , FC_DASH_AGRUP_SOL(CAB.CODPROJ, TOP.CODTIPOPER, CAB.CODCENCUS, PRJ.AD_PERFIL) AS AGRUP
    ,  PRJ.CODPROJ
     , PRJ.IDENTIFICACAO
     , CAB.NUNOTA
     , CAB.CODPARC
     , PAR.NOMEPARC
     , CAB.DTNEG AS DTFATUR
     , (SELECT TSICID.NOMECID FROM TSICID WHERE  TSICID.CODCID = PAR.CODCID) AS NOMECID
     , VEN.APELIDO
     , CAB.CODVEND
     , CAB.CODEMP
     , CUS.CODCENCUS
     , CAB.CODTIPOPER
     , PRJ.CODPROJPAI
     , PAR.CODTIPPARC
     , (SELECT MAX(PRO.CODPROD)  
          FROM TGFPRO PRO
             , TGFITE ITE
         WHERE ITE.CODPROD = PRO.CODPROD
           AND ITE.NUNOTA = CAB.NUNOTA
           AND ITE.SEQUENCIA IN (SELECT MIN(X.SEQUENCIA) FROM TGFITE X WHERE X.NUNOTA = ITE.NUNOTA)
       ) AS CODPROD
    , (SELECT DISTINCT(PRO.DESCRPROD)  
          FROM TGFPRO PRO
             , TGFITE ITE
         WHERE ITE.CODPROD = PRO.CODPROD
           AND ITE.NUNOTA = CAB.NUNOTA
           AND ITE.SEQUENCIA IN (SELECT MIN(X.SEQUENCIA) FROM TGFITE X WHERE X.NUNOTA = ITE.NUNOTA)) AS DESCRPROD
  , PAR.AD_VENDRESP as CODVENDRESP
    , VEN_PREF.CODVEND as CODVENDPREF
  FROM TGFCAB CAB
     , TSIEMP EMP
     , TGFPAR PAR
     , TGFVEN VEN
     , TCSPRJ PRJ
     , TSICUS CUS
     , TGFNAT NAT
     , TGFTOP TOP
     , TGFTPV TPV
     , TSIUSU INC
     , TSIUSU ALT
     , TGFVEN VEN_RESP
     , TGFVEN VEN_PREF
     , TGFPAR PAR_AGR
 WHERE CAB.CODEMP = EMP.CODEMP
   AND CAB.CODPARC = PAR.CODPARC
   AND CAB.CODVEND = VEN.CODVEND
   AND CAB.CODUSUINC = INC.CODUSU
   AND CAB.CODUSU = ALT.CODUSU
   AND CAB.CODPROJ = PRJ.CODPROJ
   AND CAB.CODCENCUS = CUS.CODCENCUS
   AND CAB.CODNAT = NAT.CODNAT
   AND CAB.CODTIPOPER = TOP.CODTIPOPER
   AND CAB.DHTIPOPER = TOP.DHALTER
   AND CAB.CODTIPVENDA = TPV.CODTIPVENDA
   AND CAB.DHTIPVENDA = TPV.DHALTER
   AND NVL(PAR.AD_VENDRESP,0) = NVL(VEN_RESP.CODVEND,0)
   AND NVL(PAR.CODVEND,0) = NVL(VEN_PREF.CODVEND,0)
   AND NVL(PAR.AD_CODPARCAGR,0) = NVL(PAR_AGR.CODPARC,0)  
   AND TOP.ATUALFIN = 1
   AND TOP.TIPATUALFIN = 'I'
   AND CAB.STATUSNOTA = 'L'
   AND CAB.TIPMOV IN ('V','P')
   --AND CAB.DTNEG BETWEEN '01/02/2021' AND '28/02/2021'
 GROUP BY 
       TO_CHAR(TRUNC(CAB.DTNEG,'DD'),'Mon/YYYY') 
     , TO_CHAR(TRUNC(CAB.DTNEG,'DD'),'YYYYMM') 
     , FC_DASH_AGRUP_SOL(CAB.CODPROJ, TOP.CODTIPOPER, CAB.CODCENCUS, PRJ.AD_PERFIL)
     , PRJ.CODPROJ
     , PRJ.IDENTIFICACAO
     , CAB.NUNOTA
     , CAB.CODPARC
     , PAR.NOMEPARC
     , CAB.DTNEG 
     , PAR.CODCID
     , VEN.APELIDO
     , CAB.CODVEND
     , CAB.CODEMP
     , CUS.CODCENCUS
     , CAB.CODTIPOPER
     , PRJ.CODPROJPAI
     , PAR.CODTIPPARC
   , PAR.AD_VENDRESP
     , VEN_PREF.CODVEND
      ORDER BY 1 DESC
;
