
  CREATE OR REPLACE FORCE VIEW "SANKHYA"."VW_VENDAS_GESTONLINE_SOLUTI" (CODEMP, NUNOTA, AD_IDPEDINTEG, CODPROJ, CGC_CPF, NOMEPARC, VLRNOTA, DTNEG, DTFATUR, LIST_COD_PRODUTOS, LIST_NOME_PRODUTOS, LIST_PARCELAS_FINANCEIRO, INDICADOR ) AS 
             SELECT CAB.CODEMP,
                   CAB.NUNOTA,
                   CAB.AD_IDPEDINTEG,
                   CAB.CODPROJ,
                   PAR.CGC_CPF,
                   PAR.NOMEPARC,
                   CAB.VLRNOTA,
                   CAB.DTNEG,
                   CAB.DTFATUR,
                   FC_LISTAPRODCONS(CAB.NUNOTA) AS LIST_COD_PRODUTOS,
                   FC_LISTA_NOMEPROD_PORNOTA(CAB.NUNOTA) AS LIST_NOME_PRODUTOS,
                   FC_LIST_NOTA_FINANCEIRO(CAB.NUNOTA) AS LIST_PARCELAS_FINANCEIRO,
                   NVL((SELECT CGC_CPF FROM TGFPAR WHERE CODPARC = PAR.AD_CODPARC),'NÃO TEM IND') AS INDICADOR
            FROM TGFCAB CAB, TGFPAR PAR, TGFFIN FIN
            WHERE CAB.NUNOTA = FIN.NUNOTA  
              AND CAB.CODPARC = PAR.CODPARC
              AND CAB.CODTIPOPER = 1203
              AND CAB.OBSERVACAO LIKE '%Gestão.Online%'
              AND CAB.AD_IDPEDINTEG IS NOT NULL
            --  AND ROWNUM < 9999
            GROUP BY 
                   CAB.CODEMP,
                   CAB.NUNOTA,
                   CAB.AD_IDPEDINTEG,
                   CAB.CODPROJ,
                   PAR.CGC_CPF,
                   PAR.NOMEPARC,
                   CAB.VLRNOTA,
                   CAB.DTNEG,
                   CAB.DTFATUR,
                   PAR.AD_CODPARC
            ORDER BY CAB.NUNOTA;


  GRANT INSERT ON "SANKHYA"."VW_VENDAS_GESTONLINE_SOLUTI" TO "GATEWAY";
  GRANT DELETE ON "SANKHYA"."VW_VENDAS_GESTONLINE_SOLUTI" TO "GATEWAY";
  GRANT SELECT ON "SANKHYA"."VW_VENDAS_GESTONLINE_SOLUTI" TO "GATEWAY";
  GRANT UPDATE ON "SANKHYA"."VW_VENDAS_GESTONLINE_SOLUTI" TO "GATEWAY";
