CREATE OR REPLACE FORCE VIEW "SANKHYA"."VW_NFSE_DUPGESTONLINE_SOLUTI" ("ERROPOR", "PENDENTE", "NUMNOTA", "NUMNFSE", "NUNOTA", "CODTIPOPER", "AD_CODVERIFNFSE", "DTNEG", "AD_ORIGEMINTEG", "TIPMOV", "DTFATUR", "VLRNOTA") AS 
 
SELECT 'DUPLICIDADE DE NFS-E' AS ERROPOR,
       PENDENTE,
       NUMNOTA,
       NUMNFSE,
       NUNOTA,
       CODTIPOPER,
       AD_CODVERIFNFSE,
       DTNEG,
       AD_ORIGEMINTEG,
       TIPMOV,
       DTFATUR,
       VLRNOTA
  FROM TGFCAB
 WHERE NUMNOTA IN
  (SELECT NUMNOTA
     FROM TGFCAB
    WHERE TIPMOV = 'V'
     -- AND DTNEG > '05/04/21'
      AND NUMNOTA  >= '480209'
      AND NUMNOTA  <= (SELECT MAX(NUMNOTA) FROM TGFCAB WHERE AD_ORIGEMINTEG = 'gestao_online')
      AND CODEMP = 1
      AND NUMNOTA IN (SELECT NUMNOTA FROM TGFCAB WHERE AD_ORIGEMINTEG = 'gestao_online' GROUP BY NUMNOTA)
     -- AND CODTIPOPER = 1203
      GROUP BY NUMNOTA, CODTIPOPER
      HAVING COUNT(*) > 1
 )

 UNION ALL

 SELECT 'NOTA APROVADA PENDENTE IGUAL A S' AS ERROPOR,
        PENDENTE,
        NUMNOTA,
        NUMNFSE,
        NUNOTA,
        CODTIPOPER,
        AD_CODVERIFNFSE,
        DTNEG,
        AD_ORIGEMINTEG,
        TIPMOV,
        DTFATUR,
        VLRNOTA
  FROM TGFCAB
 WHERE AD_ORIGEMINTEG = 'gestao_online'
  AND  CODEMP = 1
  AND  TIPMOV = 'V'
  AND  PENDENTE = 'S'
  AND  AD_CODVERIFNFSE IS NOT NULL
  AND  NUMNOTA <> 0
  AND  NUMNFSE IS NOT NULL
  AND  EXISTS (SELECT * FROM TGFNFSE)

 UNION ALL

 SELECT 'CAB NAO PENDENTE E ITEM PENDENTE' AS ERROPOR,
       CAB.PENDENTE,
       CAB.NUMNOTA,
       CAB.NUMNFSE,
       CAB.NUNOTA,
       CAB.CODTIPOPER,
       CAB.AD_CODVERIFNFSE,
       CAB.DTNEG,
       CAB.AD_ORIGEMINTEG,
       CAB.TIPMOV,
       CAB.DTFATUR,
       CAB.VLRNOTA
FROM TGFCAB CAB, TGFITE ITE
WHERE CAB.NUNOTA = ITE.NUNOTA
  AND CAB.AD_ORIGEMINTEG = 'gestao_online'
  AND CAB.PENDENTE = 'N'
  AND CAB.TIPMOV = 'V'
  AND CAB.NUMNOTA > 0
  AND ITE.PENDENTE = 'S'
  GROUP BY CAB.PENDENTE,
       CAB.NUMNOTA,
       CAB.NUMNFSE,
       CAB.NUNOTA,
       CAB.CODTIPOPER,
       CAB.AD_CODVERIFNFSE,
       CAB.DTNEG,
       CAB.AD_ORIGEMINTEG,
       CAB.TIPMOV,
       CAB.DTFATUR,
       CAB.VLRNOTA

UNION ALL

SELECT 'NFS-e APROVADA NA PREFEITURA E EM ATENDIMENTO NO STATUSNOTA' AS ERROPOR,
        PENDENTE,
        NUMNOTA,
        NUMNFSE,
        NUNOTA,
        CODTIPOPER,
        AD_CODVERIFNFSE,
        DTNEG,
        AD_ORIGEMINTEG,
        TIPMOV,
        DTFATUR,
        VLRNOTA
FROM TGFCAB
WHERE AD_ORIGEMINTEG = 'gestao_online'
  AND TIPMOV = 'V'
  AND PENDENTE = 'N'
  AND STATUSNOTA = 'A'
  AND AD_CODVERIFNFSE IS NOT NULL
  AND NUMNFSE IS NOT NULL

UNION ALL

SELECT 'NFS-e COM PRODUTOS DE VENDAS ALEATORIAS' AS ERROPOR,
        PENDENTE,
        NUMNOTA,
        NUMNFSE,
        G.NUNOTA,
        CODTIPOPER,
        AD_CODVERIFNFSE,
        DTNEG,
        AD_ORIGEMINTEG,
        TIPMOV,
        DTFATUR,
        VLRNOTA
FROM (
        SELECT CABPED.NUNOTA,
               CABPED.PEDCAB,
               ITEPED.PEDITE,
               (CABPED.PEDCAB - ITEPED.PEDITE) AS DIVER
        FROM
        ( SELECT CAB.NUNOTA,
                 LPAD(CAB.AD_IDPEDINTEG, 10, 0) AS PEDCAB
            FROM TGFCAB CAB, TGFITE ITE
           WHERE ITE.NUNOTA = CAB.NUNOTA
             AND CAB.TIPMOV = 'V'
             AND CAB.AD_ORIGEMINTEG = 'gestao_online'
        ) CABPED  
        ,
        (SELECT ITE.NUNOTA,
                SUBSTR(ITE.OBSERVACAO,21, 30) AS PEDITE
          FROM  TGFITE ITE
          WHERE ITE.OBSERVACAO LIKE '%Gestão.Online%'
          GROUP BY ITE.NUNOTA, SUBSTR(ite.observacao,21, 30)
        ) ITEPED
        WHERE CABPED.NUNOTA = ITEPED.NUNOTA
           ) G, TGFCAB
WHERE G.NUNOTA = TGFCAB.NUNOTA
  AND DIVER <> 0
GROUP BY PENDENTE, NUMNOTA, NUMNFSE, G.NUNOTA, CODTIPOPER, AD_CODVERIFNFSE, DTNEG, AD_ORIGEMINTEG, TIPMOV, DTFATUR, VLRNOTA

UNION ALL

SELECT 'NFS-e APROVADAS COM STATUS NFS-e DIFERENTE DE APROVADO' AS ERROPOR,
        PENDENTE,
        NUMNOTA,
        NUMNFSE,
        NUNOTA,
        CODTIPOPER,
        AD_CODVERIFNFSE,
        DTNEG,
        AD_ORIGEMINTEG,
        TIPMOV,
        DTFATUR,
        VLRNOTA
  FROM TGFCAB
 WHERE AD_ORIGEMINTEG = 'gestao_online'
  AND  CODEMP = 1
  AND  TIPMOV = 'V'
  AND  PENDENTE = 'N'
  AND  AD_CODVERIFNFSE IS NOT NULL
  AND  NUNOTA IN (SELECT NUNOTA FROM TGFNFSE)
  AND  NUMNFSE IS NOT NULL
  AND  EXISTS (SELECT * FROM TGFNFSE)
  AND  STATUSNFSE <> 'A'

UNION ALL

SELECT 'NOTAS FATURADAS E NAO COFIRMADAS' AS ERROPOR,
       PENDENTE,
       NUMNOTA,
       NUMNFSE,
       NUNOTA,
       CODTIPOPER,
       AD_CODVERIFNFSE,
       DTNEG,
       AD_ORIGEMINTEG,
       TIPMOV,
       DTFATUR,
       VLRNOTA
FROM TGFCAB
WHERE STATUSNOTA <> 'L'
  AND PENDENTE = 'N'
  AND AD_ORIGEMINTEG = 'gestao_online'
  AND TIPMOV = 'V'
  AND NUMNOTA <> 0
  AND EXISTS (SELECT * FROM TGFNFSE)

UNION ALL

SELECT 'NOTAS COM DIVERGÊNCIA NO FINANCEIRO' AS ERROPOR,
       DIVFIN.PENDENTE,
       DIVFIN.NUMNOTA,
       DIVFIN.NUMNFSE,
       DIVFIN.NUNOTA,
       DIVFIN.CODTIPOPER,
       DIVFIN.AD_CODVERIFNFSE,
       DIVFIN.DTNEG,
       DIVFIN.AD_ORIGEMINTEG,
       DIVFIN.TIPMOV,
       DIVFIN.DTFATUR,
       DIVFIN.VLRNOTA
FROM
(SELECT CAB.PENDENTE,
       CAB.NUMNOTA,
       CAB.NUMNFSE,
       CAB.NUNOTA,
       CAB.CODTIPOPER,
       CAB.AD_CODVERIFNFSE,
       CAB.DTNEG,
       CAB.AD_ORIGEMINTEG,
       CAB.TIPMOV,
       CAB.DTFATUR,
       CAB.VLRNOTA,
       SUM(ITE.VLRTOT - ITE.VLRDESC) AS VLRLIQ,
       SUM(ITE.QTDNEG) AS QTDNEG,
       (SELECT TSIEMP.CGC FROM TSIEMP WHERE CODEMP = CAB.CODEMP) AS CNPJEMP,
       ((CAB.VLRNOTA - NVL(CAB.vlrdesctotitem,0)) - NVL((SELECT SUM(VLRDESDOB) FROM TGFFIN WHERE NUNOTA = CAB.NUNOTA),0)) AS SOMAFIN
  FROM TGFCAB CAB, TGFITE ITE, TGFPAR PAR
 WHERE CAB.NUNOTA  = ITE.NUNOTA
   AND CAB.CODPARC = PAR.CODPARC
   AND CAB.AD_ORIGEMINTEG = 'gestao_online'
   AND CAB.TIPMOV = 'V'
   AND ITE.CODPROD IN (SELECT CODPROD FROM TGFPRO WHERE USOPROD <> 'M')
   --AND CAB.NUNOTA = 1761885
   GROUP BY CAB.DTNEG,   CAB.AD_IDPEDINTEG, PAR.CGC_CPF,
            CAB.CODPROJ, CAB.NUNOTA,        CAB.NUMNFSE,
            CAB.DTFATUR, CAB.VLRNOTA,       CAB.AD_CODVERIFNFSE,
            CAB.CODEMP,  CAB.PENDENTE,      CAB.NUMNFSE,
            CAB.CODTIPOPER, CAB.AD_ORIGEMINTEG, CAB.TIPMOV,
            CAB.NUMNOTA
) DIVFIN
WHERE DIVFIN.SOMAFIN > 1

UNION ALL

 SELECT 'NOTA COM CABEÇALHO MAS NÃO TEM ITEM' AS ERROPOR,
        PENDENTE,
        NUMNOTA,
        NUMNFSE,
        NUNOTA,
        CODTIPOPER,
        AD_CODVERIFNFSE,
        DTNEG,
        AD_ORIGEMINTEG,
        TIPMOV,
        DTFATUR,
        VLRNOTA
  FROM TGFCAB
 WHERE AD_ORIGEMINTEG = 'gestao_online'
  AND  CODEMP = 1
  AND  TIPMOV = 'V'
  AND  NUNOTA NOT IN (SELECT NUNOTA FROM TGFITE)

UNION ALL

 SELECT 'NFSe SEM FINANCEIRO' AS ERROPOR,
        PENDENTE,
        NUMNOTA,
        NUMNFSE,
        NUNOTA,
        CODTIPOPER,
        AD_CODVERIFNFSE,
        DTNEG,
        AD_ORIGEMINTEG,
        TIPMOV,
        DTFATUR,
        VLRNOTA
  FROM TGFCAB
 WHERE AD_ORIGEMINTEG = 'gestao_online'
  AND  CODEMP = 1
  AND  TIPMOV = 'V'
  AND  NUNOTA NOT IN (SELECT NUNOTA FROM TGFFIN)

  UNION ALL

  SELECT 'KIT COM DESCONTO - VLR DA CAB ERRADO' AS ERROPOR,
         CAB.PENDENTE,
         CAB.NUMNOTA,
         CAB.NUMNFSE,
         CAB.NUNOTA,
         CAB.CODTIPOPER,
         CAB.AD_CODVERIFNFSE,
         CAB.DTNEG,
         CAB.AD_ORIGEMINTEG,
         CAB.TIPMOV,
         CAB.DTFATUR,
         CAB.VLRNOTA
FROM TGFCAB CAB, TGFITE ITE
WHERE CAB.NUNOTA = ITE.NUNOTA
  AND CAB.AD_IDPEDINTEG IS NOT NULL
  AND CAB.OBSERVACAO LIKE '%Gestão.Online%'
  AND ITE.USOPROD IN ('D', 'M', 'B')
  AND ITE.VLRDESC > 0

ORDER BY NUMNOTA DESC;

