
  CREATE OR REPLACE FORCE VIEW "SANKHYA"."VW_VENDA_COMISSAOGESTAOON_SOL" ("CODEMP", "NUNOTA", "CODPROJ", "CGC_CPF", "NOMEPARC", "TELEFONE", "EMAIL", "ENDERECO", "BAIRRO", "CIDADE_UF", "CEP", "VLRNOTA", "DTNEG", "DTFATUR", "LIST_COD_PRODUTOS", "LIST_NOME_PRODUTOS", "LIST_FIN", "INDICADOR", "DTALTER") AS 
  SELECT CAB.CODEMP,
           CAB.NUNOTA,
           CAB.CODPROJ,
           PAR.CGC_CPF,
           PAR.NOMEPARC,
           PAR.TELEFONE,
           NVL(PAR.EMAIL, PAR.EMAILNFSE) AS EMAIL,
           (SELECT TSIEND.NOMEEND FROM TSIEND WHERE CODEND = PAR.CODEND) AS ENDERECO,
           (SELECT TSIBAI.NOMEBAI FROM TSIBAI WHERE CODBAI = PAR.CODBAI) AS BAIRRO,
           (SELECT TSICID.NOMECID||' - '||
                  (SELECT TSIUFS.UF FROM TSIUFS WHERE CODUF = TSICID.UF)
            FROM TSICID WHERE CODCID = PAR.CODCID ) AS CIDADE_UF,
           PAR.CEP AS CEP,
           CAB.VLRNOTA,
           CAB.DTNEG,
           CAB.DTFATUR,
           FC_LISTAPRODCONS (CAB.NUNOTA) AS LIST_COD_PRODUTOS,
           FC_LISTA_NOMEPROD_PORNOTA(CAB.NUNOTA) AS LIST_NOME_PRODUTOS,
           FC_LIST_NOTA_FINANCEIRO(CAB.NUNOTA) AS LIST_FIN,
           NVL((SELECT CGC_CPF FROM TGFPAR WHERE CODPARC = PAR.AD_CODPARC),'NÃO TEM IND') AS INDICADOR,
           MAX(FIN.DTALTER) AS DTALTER
    FROM TGFCAB CAB, TGFPAR PAR, TGFFIN FIN
    WHERE CAB.NUNOTA = FIN.NUNOTA  
      AND CAB.CODPARC = PAR.CODPARC
      AND CAB.CODTIPOPER = 1900
      --AND CAB.DTFATUR BETWEEN :DTINI AND :DTFIN
      --AND CAB.DTFATUR BETWEEN '01/10/21' AND '31/10/21'
      AND FIN.VLRBAIXA > 0
      AND FIN.DHBAIXA IS NOT NULL
      AND CAB.CODPROJ IN (SELECT CODPROJ FROM AD_PARAMETROPRJ WHERE NUPARAMETRO = 174 GROUP BY CODPROJ)
    GROUP BY 
           CAB.CODEMP,
           CAB.NUNOTA,
           CAB.CODPROJ,
           PAR.CGC_CPF,
           PAR.NOMEPARC,
           CAB.VLRNOTA,
           CAB.DTNEG,
           CAB.DTFATUR,
           PAR.AD_CODPARC,
           PAR.TELEFONE,
           PAR.EMAIL, 
           PAR.EMAILNFSE,
           PAR.CODEND,
           PAR.CODBAI,
           PAR.CODCID,
           PAR.CEP
    ORDER BY CAB.NUNOTA;

